# Generated by Django 2.1.5 on 2020-08-14 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trecord',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date'),
            preserve_default=False,
        ),
    ]
